### ISSUE TITLE
EnvironmentVariablesError("BOT_TOKEN");

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [elizandrodantas/bot-blaze-telegram#1]
Obtive esse erro ao iniciar, mas o Token está correto e já o uso em outro bot!

> bot-blaze-telegram@0.1.0 start
> node src/index.mjs

  ____  _                          _ _   _       _____    _
 | __ )| | __ _ _______  __      _(_) |_| |__   |_   _|__| | ___  __ _ _ __ __ _ _ __ ___
 |  _ \| |/ _` |_  / _ \ \ \ /\ / / | __| '_ \    | |/ _ \ |/ _ \/ _` | '__/ _` | '_ ` _ \
 | |_) | | (_| |/ /  __/  \ V  V /| | |_| | | |   | |  __/ |  __/ (_| | | | (_| | | | | | |
 |____/|_|\__,_/___\___|   \_/\_/ |_|\__|_| |_|   |_|\___|_|\___|\__, |_|  \__,_|_| |_| |_|
                                                                 |___/
       by: Elizandro Dantas

- Iniciando servidorfile:///C:/Users/SERVIDOR/Desktop/Bot2/bot-blaze-telegram/src/core/telegram.mjs:30
        throw new EnvironmentVariablesError("BOT_TOKEN");
              ^

EnvironmentVariablesError: error environment veriables: [BOT_TOKEN]
    at new Telegram (file:///C:/Users/SERVIDOR/Desktop/Bot2/bot-blaze-telegram/src/core/telegram.mjs:30:15)
    at new BotBlazeWithTelegram (file:///C:/Users/SERVIDOR/Desktop/Bot2/bot-blaze-telegram/src/middleware/bot.mjs:16:21)
    at start (file:///C:/Users/SERVIDOR/Desktop/Bot2/bot-blaze-telegram/src/index.mjs:23:25)
    at file:///C:/Users/SERVIDOR/Desktop/Bot2/bot-blaze-telegram/src/index.mjs:14:5
    at C:\Users\SERVIDOR\Desktop\Bot2\bot-blaze-telegram\node_modules\figlet\lib\figlet.js:858:13
    at C:\Users\SERVIDOR\Desktop\Bot2\bot-blaze-telegram\node_modules\figlet\lib\node-figlet.js:30:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v17.8.0

**Comment by elizandrodantas** [comment]
Esse erro é nas variáveis ambiente, citada em [Instalação#Variaveis Ambiente#3](https://github.com/elizandrodantas/bot-blaze-telegram#instala%C3%A7%C3%A3o)

### Soluções:

1. Você pode alterar nome do arquivo **.env.example** para **.env** e preenche os campos [BOT_TOKEN e ID_GROUP_MESSAGE]
2. Setar variaveis de ambiente no sistema (você pode pesquisar mais sobre no google)

### Uso em dev
- yarn
```sh
yarn dev
```
- npm
```sh
npm run dev
```

Obs.: apenas o script de **dev** consegue implementar as variáveis ambiente do arquivo **.env** no sistema, caso execute outro arquivo/script preciso setar direto no sistema.

Mais sobre [variáveis ambiente](https://blog.rocketseat.com.br/variaveis-ambiente-nodejs/) nodejs

**Comment by CentroEducacional-CEC** [comment]
Já o tinha feito, hoje ao tentar novamente vi que o problema era a forma que eu estava tentando iniciar o bot! a correta é com esse comando!

node example/example-with-dotenv.mjs
