### ISSUE TITLE
Troca das Figurinhas

### ISSUE THREAD

**Issue by DinhoNunesLC** [elizandrodantas/bot-blaze-telegram#10]
A opção para troca de figurinhas em versões anteriores era aqui! (pelo menos onde eu trocava).

`sticker: {
	winNotGale: "",
        winGaleOne: "",
        winGaleTwo: "",
	winWhite: "",
        loss: "",
    },`

Eu utilizo dessa forma.

`sticker: {
	winNotGale: "1entrada.webp",
        winGaleOne: "2entrada.webp",
        winGaleTwo: "3entrada.webp",
	winWhite: "winb.webp",
        loss: "loss.webp",
    },`

Nessa nova versão não encontrei  a opção do `GaleTwo ` que no meu caso sinaliza a 3ª entrada/tentativa, para trocar a figurinha. Foi removida? É possível trazer de volta? É um recurso interessante!

**Comment by elizandrodantas** [comment]
Sim é possivel, mas preciso fazer algumas alterações no codigo. A função [_getStickerOfOptions](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/middleware/bot.mjs#L493) quem obtem os nomes setados nas opções, e envia para o telegram. Com conhecimento basico creio que de pra fazer essa modificação, compara os commit e observa as modificações que foi feita nessa ultima atualização.

Qualquer duvida especifica, so mandar que a gente tira essa duvida
