### ISSUE TITLE
Segundo Gale.

### ISSUE THREAD

**Issue by DinhoNunesLC** [elizandrodantas/bot-blaze-telegram#11]
O segundo gale (Terceira entrada) foi removido, ou apenas a mensagem referente a ele?

**Comment by DinhoNunesLC** [comment]
Confirmada a remoção do segundo gale (terceira entrada). Com isso a assertividade do bot caiu de 90% a 98% para 74% a 86%.

**Comment by jvcunha777** [comment]
> Confirmada a remoção do segundo gale (terceira entrada). Com isso a assertividade do bot caiu de 90% a 98% para 74% a 86%.

Sério que tirou? Eu ainda tenho o bot com 3 gale

**Comment by ybadnews** [comment]
> > Confirmada a remoção do segundo gale (terceira entrada). Com isso a assertividade do bot caiu de 90% a 98% para 74% a 86%.
> 
> Sério que tirou? Eu ainda tenho o bot com 3 gale

Não removeu, vai no caminho __test__/bot.test.mjs

Linha 40> gale: 1 (altera pra 2).

Simples

**Comment by elizandrodantas** [comment]
A quantidade de gales agora são passada nas opções. Todas as opções estão no README do repositorio, incluse [como usar](https://github.com/elizandrodantas/bot-blaze-telegram#todas-op%C3%B5es-com-forma-de-uso)

**Comment by DinhoNunesLC** [comment]
@ybadnews eu não executo com npm run dev mas sim como example/example-with-dotenv.mjs acredito que deveria ser no bot.mjs do src a troca da quantidade de gales. Se sim, sabe qual a linha?

**Comment by ybadnews** [comment]
> @ybadnews eu não executo com npm run dev mas sim como example/example-with-dotenv.mjs acredito que deveria ser no bot.mjs do src a troca da quantidade de gales. Se sim, sabe qual a linha?

Eu tbm não. Executa usando node __test__/bot.test.mjs

Mais fácil pra gerenciar msg, stickers e gales. (Verifica se o __ foi certo, estou no cell)

**Comment by ybadnews** [comment]
> > @ybadnews eu não executo com npm run dev mas sim como example/example-with-dotenv.mjs acredito que deveria ser no bot.mjs do src a troca da quantidade de gales. Se sim, sabe qual a linha?
> 
> Eu tbm não. Executa usando node __test__/bot.test.mjs
> 
> Mais fácil pra gerenciar msg, stickers e gales. (Verifica se o __ foi certo, estou no cell)

![image](https://user-images.githubusercontent.com/104029442/193721317-a2af9a6c-78fa-4af4-bfae-593289644615.jpeg)
