### ISSUE TITLE
erro Parâmetro inválido - example-with-dotenv.mjs

### ISSUE THREAD

**Issue by andrelmariano** [elizandrodantas/bot-blaze-telegram#15]
alguém consegue ajudar ? e tbm como conseguir o ID do grupo, não tenho certeza que peguei o correto.

**Comment by ybadnews** [comment]
Adiciona o bot no seu canal/grupo.
Vai no seu bot e clica no botão start.

Depois copia esse link e coloca o token do seu bot: https://api.telegram.org/botTOKENAQUI/getUpdates

manda alguma mensagem no grupo em que o bot está, dps da F5 no link da api com seu token.
irá aparecer o id do group, id da msg e id de quem mandou, só vc copiar o id group.

tenta aí, abs.

**Comment by andrelmariano** [comment]
@ybadnews quando eu mando no grupo não atualiza nessa url, quando eu mando no bot, ai ele pega os dados, mas não tenho o group id

**Comment by ybadnews** [comment]
repara bem no link que te mandei, você apagou a msg bot antes do token

**Comment by ybadnews** [comment]
> -803151858

de acordo com essa msg, o id do grupo é o -803151858

**Comment by andrelmariano** [comment]
@ybadnews 
eu coloquei ele lá mas estou com esse erro do print acima.

**Comment by ybadnews** [comment]
> @ybadnews eu coloquei ele lá mas estou com esse erro do print acima.

entre em contato cmg no Discord, resolvendo, você encerra aqui. BadNews#8127
