### ISSUE TITLE
onde eu usor o import?

### ISSUE THREAD

**Issue by jvcunha777** [elizandrodantas/bot-blaze-telegram#18]
![Anotação 2022-10-22 144134](https://user-images.githubusercontent.com/112199293/197355131-968e207e-ccdc-4d8e-8dba-3f27d0834cc2.png)

import { BotBlazeWithTelegram } from './src/index.mjs';

new BotBlazeWithTelegram(options).run();
onde uso isso?

**Comment by matheusvcarvalho** [comment]
inicia direto na pasta examples
node example-with-dotenv.mjs ou example-without-dotenv.mjs

**Comment by CentroEducacional-CEC** [comment]
Executou `npm install` ?

**Comment by elizandrodantas** [comment]
com a nova versão, você vai instalar o bot como um package do npm. os import foram atualizados no readme

## Instação
https://github.com/elizandrodantas/bot-blaze-telegram#instala%C3%A7%C3%A3o-e-configura%C3%A7%C3%B5es

## Import
https://github.com/elizandrodantas/bot-blaze-telegram#uso
