### ISSUE TITLE
Bot não encaminha mensagem para canal

### ISSUE THREAD

**Issue by bladeofcl** [elizandrodantas/bot-blaze-telegram#19]
Olá, estou usando a versão mais recente e o bot não envia mensagem no canal
ja tentei colocar com - e apenas a numeração mesmo assim não deu certo.
Coloquei também o bot como adm mais mesmo assim não foi.

**Comment by DinhoNunesLC** [comment]
Use -100 junto ao id do canal ou grupo!

**Comment by DinhoNunesLC** [comment]
Após fazer uma instalação em uma VPS os sinais deixaram de ser enviados, apenas a checagem está sendo enviada!

VPS UBUNTO 20.10 ATLANTA
NODE v18.7.0

Em localhost está totalmente normal.
