### ISSUE TITLE
como resolver isso?

### ISSUE THREAD

**Issue by jvcunha777** [elizandrodantas/bot-blaze-telegram#2]
Microsoft Windows [versão 10.0.19042.1706]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\pc\Desktop\bot-blaze-telegram-main>npm start

> bot-blaze-telegram@0.1.0 start
> node src/index.mjs

node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'express' imported from C:\Users\pc\Desktop\bot-blaze-telegram-main\src\index.mjs
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:951:9)
    at moduleResolve (node:internal/modules/esm/resolve:1000:20)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

C:\Users\pc\Desktop\bot-blaze-telegram-main>

**Comment by elizandrodantas** [comment]
As dependencias não foram instaladas. segundo passo da [instalação](https://github.com/elizandrodantas/bot-blaze-telegram#instala%C3%A7%C3%A3o)

**Comment by jvcunha777** [comment]
![1](https://user-images.githubusercontent.com/112199293/186966144-47d82e66-a2b2-437f-8c7d-71dca161b1b9.png)

esse problema do bot é a porta ?

**Comment by elizandrodantas** [comment]
Problema que pra rodar em produção `npm start` as variaveis ambiente precisa esta setado no sistema. pra usar localmente, a solução é usar o comando `npm run dev` or `yarn dev`

**Comment by jvcunha777** [comment]
deu certo parece
![1](https://user-images.githubusercontent.com/112199293/186966935-ffbe9d5b-3f03-4c12-93f2-a96454367ca6.png)

**Comment by jvcunha777** [comment]
![2](https://user-images.githubusercontent.com/112199293/186967159-181427f9-8700-45af-b93d-79d11b2fbf2a.jpg)
deu certo parece

**Comment by elizandrodantas** [comment]
Sim, esta rodando.

**Comment by jvcunha777** [comment]
porem, o bot ta rodando, mas as mensagem nao chega no grupo, o erro é no token? ou no id? pra achar o id do grupo usa o bot q eu mostrei na imagem de cima?

**Comment by elizandrodantas** [comment]
em grupos o **-** tambem esta incluso no ID. ex.:  _**-123456789**_

**Comment by elizandrodantas** [comment]
> em grupos o **-** tambem esta incluso no ID. ex.: _**-123456789**_

nesse teu caso: **-795844460**
