### ISSUE TITLE
Padrões de analise.

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [elizandrodantas/bot-blaze-telegram#22]
Os padrões para analise personalizada (unitaria) e (multiplas) não se encontra no arquivo [analise.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/core/analise.mjs).

Os mesmos estão apenas no arquivo [bot.test.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/__test__/bot.test.mjs).

Para quem inicia a partir do [example-with-dotenv.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/example/example-with-dotenv.mjs) alterar o que está em [bot.test.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/__test__/bot.test.mjs) vai trocar os padrões?

**Comment by elizandrodantas** [comment]
os arquivos são apenas para desenvolvimento (__test__) e para exemplo (example), so um complemento nos que esta no README. 

vc pode copiar o que está la em bot.test.mjs,

**Comment by CentroEducacional-CEC** [comment]
Outra coisa, trocar o { color: "black" } por { color: "white" } não funciona, seria uma opção para adicionarmos padrões do branco!

Além de adicionar uma cor neutra quando não importa a cor que sair! Seguindo esse padrão onde a cor azul é apenas uma casa, não importa se é preto ou vermelho.

⚪️🔵🔵🔵🔵 -> Entrada no ⚪️

**Comment by opabloaraujo** [comment]
se trocar a cor pelo numero é possivel?

**Comment by CentroEducacional-CEC** [comment]
Número no lugar da cor, não tentei!

Para contar os brancos que sairam use isso! ${number.white}

**Comment by elizandrodantas** [comment]
> Outra coisa, trocar o { color: "black" } por { color: "white" } não funciona, seria uma opção para adicionarmos padrões do branco!
> 
> Além de adicionar uma cor neutra quando não importa a cor que sair! Seguindo esse padrão onde a cor azul é apenas uma casa, não importa se é preto ou vermelho.
> 
> ⚪️🔵🔵🔵🔵 -> Entrada no ⚪️

Creio que isso seja um bug, vou verificar

**Comment by elizandrodantas** [comment]
> se trocar a cor pelo numero é possivel? no resumo, tem como colocar o calculo de quantos brancos sairam?

apenas quantos wins de brancos foram contabilizados, ele não mentaliza todos os brancos sairam
