### ISSUE TITLE
Possível Bug

### ISSUE THREAD

**Issue by DinhoNunesLC** [elizandrodantas/bot-blaze-telegram#23]
Após a ultima atualização, ao iniciar com `node example/example-with-dotenv.mjs` recebo isso no console.

√ bot iniciado com sucesso :)
√ Tudo certo com o chat_id :)
√ Iniciado com sucesso!
[15/12/2022 16:44:17] status: Rodada Finalizada
2 undefined
0 undefined
1 undefined
0 undefined
2 undefined
1 undefined
1 undefined
2 undefined
2 undefined
[15/12/2022 16:44:22] status: Jogadores Apostando

Esse `undefined` se repete todas as vezes que a rodada é finalizada.

**Comment by CentroEducacional-CEC** [comment]
O mesmo ocorreu aqui!

**Comment by opabloaraujo** [comment]
mesmo por aqui
