### ISSUE TITLE
fiz a instalação do bot deu tudo certo mas as msg n chegam no telegram

### ISSUE THREAD

**Issue by Caveiranegra211** [elizandrodantas/bot-blaze-telegram#29]

**Comment by DinhoNunesLC** [comment]
Estou com o mesmo problema!
Acredito ser algo com a VPS
Está usando de qual região?

**Comment by DinhoNunesLC** [comment]
Após fazer uma instalação em uma VPS os sinais deixaram de ser enviados, apenas a checagem está sendo enviada!

VPS UBUNTU 20.10 ATLANTA
NODE v18.7.0

Em localhost está totalmente normal.

**Comment by Caveiranegra211** [comment]
eu n uso vps como uso local host?

**Comment by DinhoNunesLC** [comment]
Você disse que fez a instalação, fez onde?

**Comment by Caveiranegra211** [comment]
poderia ser mais especifico? mas acho que entendi a pergunta, eu usei npm install, e instalei peplo node/EXAMPLE

**Comment by DinhoNunesLC** [comment]
Localhost é seu computador.

**Comment by Caveiranegra211** [comment]
sim eu fiz eu n usei vps e msm assim os sinais n chegam e o bot aparece que n aceita msg privada

**Comment by DinhoNunesLC** [comment]
Siga esses passos para a instalação!

Instale o Git e o NodeJS

Abra o CMD e execute o código.
> git clone https://github.com/elizandrodantas/bot-blaze-telegram

Abra a pasta com esse comando
> cd bot-blaze-telegram

Instale as dependências
> npm install bot-blaze-telegram

Troque o nome do arquivo .env.example para .env

Adicione nesse mesmo arquivo as informações

BOT_TOKEN="" 
ID_GROUP_MESSAGE=""

Execute com a opção desejada, eu uso essa.
> node example/example-with-dotenv.mjs

Obs...
1 - Não importa se é Grupo ou canal.
2 - O bot tem de estar como administrador.
3 - Envie você mesmo uma mensagem no grupo ou canal antes de usar o bot pela primeira vez, pode ser um simples ponto.

**Comment by DinhoNunesLC** [comment]
![image](https://user-images.githubusercontent.com/57111364/214172327-b582906d-08f1-4637-adad-1b753a8b367a.png)

Aqui em localhost, e já com meus padrões! Em VPS não foi possível usar justamente por não chegar as mensagens!

**Comment by Caveiranegra211** [comment]
como que eu altero o nome pra env no git?

**Comment by DinhoNunesLC** [comment]
Se estiver no Windows pode usar isso no cmd.

> ren .env.example .env

Ou use gerenciador de arquivos, troque o nome como você trocaria de qualquer coisa!

**Comment by Caveiranegra211** [comment]
tem que colocar url? e api?

**Comment by DinhoNunesLC** [comment]
Não, apenas siga os paços que eu mencionei!

Se fizer algo a mais, dará errado, se fizer algo a menos, dará errado!

**Comment by Caveiranegra211** [comment]
deu issso  Iniciando aplicação[!required] Token do BOT TELEGRAM: [00000000:ad4f6a77...]

**Comment by DinhoNunesLC** [comment]
Você pulou a parte de adicionar as informações do BOT e do CANAL/GRUPO. Abra o arquivo .env e o faça!

**Comment by Caveiranegra211** [comment]
eu mudei pelo bloco de notas

**Comment by DinhoNunesLC** [comment]
Ok, se você salvou o arquivo e adicionou as informações corretamente, já está funcionando!

**Comment by Caveiranegra211** [comment]
![2023-01-23](https://user-images.githubusercontent.com/123283213/214176495-ddb988ff-2339-4e18-8c14-85fad8ac313a.png)
eu estou tentando refazer mas aparece que ja existe como posso apagar de vez e refaze4?

**Comment by DinhoNunesLC** [comment]
Basta apagar a pasta. bot-blaze-telegram

**Comment by CentroEducacional-CEC** [comment]
> Siga esses passos para a instalação!
> 
> Instale o Git e o NodeJS
> 
> Abra o CMD e execute o código.
> 
> > git clone https://github.com/elizandrodantas/bot-blaze-telegram
> 
> Abra a massa com esse comando
> 
> > cd bot-blaze-telegram
> 
> Instale as dependências
> 
> > npm install bot-blaze-telegram
> 
> Troque o nome do arquivo .env.example para .env
> 
> Adicione nesse mesmo arquivo as informações
> 
> BOT_TOKEN="" ID_GROUP_MESSAGE=""
> 
> Execute com a opção desejada, eu uso essa.
> 
> > nó exemplo/exemplo-com-dotenv.mjs
> 
> Obs... 1 - Não importa se é Grupo ou canal. 2 - O bot tem de estar como administrador. 3 - Envie você mesmo uma mensagem no grupo ou canal antes de usar o bot pela primeira vez, pode ser um simples ponto.

Um baita tutorial, seria interessante adicionar ele ao README do projeto.

**Comment by CentroEducacional-CEC** [comment]
Já pode dar como encerrada?

**Comment by pfmlima** [comment]
Bom dia, segui todos os passos corretamente..
criei o canal.. criei o bot.. coloquei o bot como admin e porem na hora de executar ainda recebo o erro

![image](https://user-images.githubusercontent.com/123647379/214857401-ccf08b83-5c38-4bf9-bd9f-2811bcacaf10.png)

**Comment by pfmlima** [comment]
> Já pode dar como encerrada?

nooooo

**Comment by DinhoNunesLC** [comment]
É justamente o que está escrito aí! Chat ID inválido, ou o bot não tem permissão para enviar mensagem.

**Comment by DinhoNunesLC** [comment]
![Screenshot_20230126-111710](https://user-images.githubusercontent.com/57111364/214859025-5e1e0a4d-367c-4d81-a2b7-6b16b1b1de34.png)

Veja, o ID é esse número abaixo do nome do grupo/canal você tem que adicionar o -100 no início desse número.

**Comment by DinhoNunesLC** [comment]
Sim, o mesmo usuário daqui! @DinhoNunesLC

**Comment by pfmlima** [comment]
refiz canal, criei novo bot. segue passo a passo no detalhe e ainda com mesmo erro

**Comment by CentroEducacional-CEC** [comment]
Ok, mas Não é melhor pegar diretamente no telegram, sem a nesessidade outras plataformas?
Enfim! Já pode dar como encerrado.

**Comment by OsGuri** [comment]
![Captura de tela_20230128_175116](https://user-images.githubusercontent.com/110336890/215290618-5a69bd6f-ab6e-481b-bac6-e5c68fa2ef6a.png)

Aqui deu tudo certo, mas após 15 minutos rodando eu esse erro e não sei como resolver

**Comment by DinhoNunesLC** [comment]
Algo está bloqueando seu acesso a api.

Pode ser falha na conexão.
Firewall
E várias outras coisas. Não é problema no bot! Tenho uma rodando em uma sala grátis 24h.

**Comment by Caveiranegra211** [comment]
N ENCERRA

**Comment by DinhoNunesLC** [comment]
?

**Comment by Caveiranegra211** [comment]
o meu problema continua

**Comment by Caveiranegra211** [comment]
![2023-01-29 (1)](https://user-images.githubusercontent.com/123283213/215353474-c07473be-c220-44c5-a35d-915a0dfd0605.png)
![2023-01-29](https://user-images.githubusercontent.com/123283213/215353486-d1e8fac4-4361-49f5-8de8-62a78422642f.png)

**Comment by Caveiranegra211** [comment]
supostamente deu tudo certo mas as mensagens não chegam no canal telegram

**Comment by DinhoNunesLC** [comment]
Tente as seguintes opções.

Refazer a instalação, guarde o arquivo .env para não precisar fazer configurações novamente.

Execute diretamente pelo cmd.

Use a versão mais recente do node.

Se não resolver, troque de aparelho.

**Comment by DinhoNunesLC** [comment]
Pelo que vi, seu relógio está algumas horas a frete do horário de Brasília. Se você não está no Brasil, verifique se seu país bloqueia o acesso a Blaze.

**Comment by Caveiranegra211** [comment]
n bloqueia eu tou morando em portugal e aqui a blaze vai de boa
mas sera que a api muda de região?

**Comment by DinhoNunesLC** [comment]
Eu perguntei sua região na primeira mensagem, já poderíamos ter resolvido isso, e evitado tanta mensagem! Compre uma VPS brasileira, e funcionará sem problemas, você também pode buscar a api de Portugal. Acredito que seja esse o problema.

**Comment by Caveiranegra211** [comment]
pode me recomendar uma vps? e sabe como eu faço para achar uma api portuguesa da blaze?

**Comment by DinhoNunesLC** [comment]
Vps tem várias, procure a que você deseja usar. Já usei Master da Web, hoje uso AWS.

**Comment by Caveiranegra211** [comment]
mano eu so meio leigo no assunto mas o q a minha região  compromete no envio dos sinais do bot para o telegram?

**Comment by DinhoNunesLC** [comment]
Acredito que o primordial é o horário, mas é um chute.

**Comment by Caveiranegra211** [comment]
e se eu simplesmente  mudar o horario do pc?

**Comment by DinhoNunesLC** [comment]
Tente todas as possibilidades, se não conseguir, volte.

**Comment by Caveiranegra211** [comment]
como que eu configuro o bot na vps?

**Comment by DinhoNunesLC** [comment]
Do mesmo jeito que fez no computador. Também já enviei o passo a passo logo acima.

**Comment by Caveiranegra211** [comment]
existe alguma vps gratuita pra eu experimentar e ver se resulta?

**Comment by DinhoNunesLC** [comment]
AWS

**Comment by cleitonrei** [comment]
confere o local do servidor, em servidor localizado nos Estados Unidos por exemplo, não funciona
