### ISSUE TITLE
SAFE AFTER WIN

### ISSUE THREAD

**Issue by ybadnews** [elizandrodantas/bot-blaze-telegram#3]
Olá,

Como faço pra colocar um tempo depois de um WIN ? pois ele está toda hora mandando sinais.

**Comment by elizandrodantas** [comment]
Não adicionei essa opção, so adicionei opção pra ele dar tempo quando resultado for LOSS. Pode fazer essa modificação, exemplo do LOSS: [chamada](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/middleware/bot.mjs#L133) e [função](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/middleware/bot.mjs#L213)

**Comment by ybadnews** [comment]
Infelizmente não consegui, tentei adicionar uma function de sleep após o retorno de envio, porém iniciou a aposta sem respeitar.

Estou tentando "mesclar" a função do after_loss usando uma nova chamada, SAFE_AFTER_WIN. Porém, sem sucesso.

Preciso de uma ajuda, ta difícil entender.

Abs

**Comment by elizandrodantas** [comment]
Da uma olhadinha melhor no código, vê se consegue fazer a alteração mano. Já tem um modelos, só tentar copiar. 🤖👨‍💻

**Comment by elizandrodantas** [comment]
Caso queira modificar da forma que você quiser, me chama em alguns dos contatos que a gente faz negócio. 👊🏽

**Comment by ybadnews** [comment]
Não sou forte no JS, desculpe.
Tentei copiar e realmente não vai.. estou travando nos result.

Realmente essa função de time depois de qualquer win iria me ajudar muito. 
Foi mal lhe atrapalhar, mas se tiver uma forma de eu entrar em contato (te mandei mensagem no instagram) pra podermos colocar esse time no código (nem que seja copy/paste do loss).

Abs
Meu discord: BadNews#8127

**Comment by elizandrodantas** [comment]
estou atualizando, fica de olho..

**leave the little star**
