### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Zy0exe** [elizandrodantas/bot-blaze-telegram#30]
Hey there i was wondering if there was a way to contact you, i'd like to ask some questions privately

my discord is: NotZyo#1032
and my email is: zyoisbad@gmail.com

**Comment by elizandrodantas** [comment]
> Hey there i was wondering if there was a way to contact you, i'd like to ask some questions privately
> 
> 
> 
> my discord is: NotZyo#1032
> 
> and my email is: zyoisbad@gmail.com

email: dantaspm@icloud.com
discord: Hype#5026
