### ISSUE TITLE
Api offline! api-v2.blaze.com

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [elizandrodantas/bot-blaze-telegram#31]

**Comment by elizandrodantas** [comment]
a host citada, é a que recebe as rodadas via websocket, e aqui esta tudo ok. verifica se não é algum problema na sua conexão. segue imagens: 

https://prnt.sc/Ee2wc-Zq0KAB

**Comment by DinhoNunesLC** [comment]
Esse problema foi temporário, ocorreu na madrugada, e retornou por volta de 13:30h.

**Comment by elizandrodantas** [comment]
> Esse problema foi temporário, ocorreu na madrugada, e retornou por volta de 13:30h.

São percas de conexão, pode ocorrer ate por uma oscilação na rede. Problema maior é que para todo o processo. Mas agora ele ta tratando esse erro de uma forma diferente

**Comment by DinhoNunesLC** [comment]
![Screenshot_20230218-155720](https://user-images.githubusercontent.com/57111364/219883638-65edefaa-d216-4bc5-a21f-52c84e311f8b.png)

Retornou aqui, em localhost e na vps (vps localizada no Brasil).

**Comment by elizandrodantas** [comment]
> ![Screenshot_20230218-155720](https://user-images.githubusercontent.com/57111364/219883638-65edefaa-d216-4bc5-a21f-52c84e311f8b.png)
> 
> Retornou aqui, em localhost e na vps (vps localizada no Brasil).

atualizou?

**Comment by elizandrodantas** [comment]
aqui forcei um erro desconectando minha rede, so que ao reconectar ele volta ao normal. vou deixar ele rodar mais um pouco pra ve se da algum erro sem forçar: 

https://prnt.sc/b-ZIlRePHrA1

**Comment by DinhoNunesLC** [comment]
Eu início com `node example/example-with-dotenv.mjs` pois lá consegui fazer algumas mudanças nas mensagens que são enviadas no canal/grupo. Vou tentar iniciar de outra forma.

**Comment by elizandrodantas** [comment]
> Eu início com `node example/example-with-dotenv.mjs` pois lá consegui fazer algumas mudanças nas mensagens que são enviadas no canal/grupo. Vou tentar iniciar de outra forma.

A forma de iniciar não muda nada, so as opções do usaurio

**Comment by DinhoNunesLC** [comment]
Infelizmente o problema continua na VPS, mas em localhost está ok!

Refazendo a instalação da VPS e logo mais retorno com a possível solução.

**Comment by DinhoNunesLC** [comment]
Já pode fechar, o problema na VPS foi resolvido com uma nova instalação!
