### ISSUE TITLE
Alterar mensagens

### ISSUE THREAD

**Issue by Pegoraroz** [elizandrodantas/bot-blaze-telegram#34]
Eu vi que na parte da instalação tem várias coisas que podem ser modificadas, estava tentando modificar o layout das mensagens para uma forma que ficasse mais agradável pra mim, acontece duas coisas:

1. salvo mas não altera nada
2. não salva e diz que não sou o dono do arquivo

estava modificando o arquivo :message.mjs
localizado na pasta: src/static/message.mjs

**Comment by elizandrodantas** [comment]
arquivo de manipulação deve está errado. pode esta executando um e executando outro
