### ISSUE TITLE
No admin premission

### ISSUE THREAD

**Issue by hulkerbr** [elizandrodantas/bot-blaze-telegram#36]
ta me dando esse erro alguem consegue ajudar?

✔ bot iniciado com sucesso :)
✔ tudo certo com o chat_id :)
⠇ Iniciando aplicaçãofile:///C:/Users/hulk/bot-blaze-telegram/src/middleware/bot.mjs:262
        throw new Error("no admin permission (blaze");
              ^

Error: no admin permission (blaze
    at BotBlazeWithTelegram.run (file:///C:/Users/hulk/bot-blaze-telegram/src/middleware/bot.mjs:262:15)
    at async start (file:///C:/Users/hulk/bot-blaze-telegram/example/example-with-dotenv.mjs:55:5)

**Comment by elizandrodantas** [comment]
api da balze não permite acesso da sua área (identificada por ip)

**Comment by hulkerbr** [comment]
Como posso fazer para solucionar esse problema?

**Comment by elizandrodantas** [comment]
tenta trocar o host da api

https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/core/blaze.mjs#L205

Linha 205, substitui `blaze.com` por `blaze-3.com`

**Comment by CentroEducacional-CEC** [comment]
Já pode fechar!
