### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by jvcunha777** [elizandrodantas/bot-blaze-telegram#4]
Queria saber como pego a roll, que mostra os número das cores e coloco pro bot informa no telegram

**Comment by elizandrodantas** [comment]
não compreendi, pode refazer a pergunta

**Comment by jvcunha777** [comment]
[27/08/2022 19:43:07] status: round performed, result: [color: vermelho - roll: 2]
opa, esse "roll" é o numero da cor q sai, no caso eu queria q aparecesse no bot do telegram a mensagem, EX: após o numero 2 entrar no preto e branco
onde fica esse 'roll' pra eu chamar ele ??

**Comment by elizandrodantas** [comment]
Pelo que entendi, você quer mudar a regra da analise do bot, pra isso, so alterar o arquivo [analise.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/core/analise.mjs).

**Comment by jvcunha777** [comment]
> Pelo que entendi, você quer mudar a regra da analise do bot, pra isso, so alterar o arquivo [analise.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/core/analise.mjs).

Eu só quero q aparece na mensagem do bot o numero da ultima cor ![Screenshot_20220827-230730_Telegram.jpg](https://user-images.githubusercontent.com/112199293/187054450-7e28441f-759f-417f-b985-39c8af5efda2.jpg)

**Comment by elizandrodantas** [comment]
Esta opção não está inclusa no código, só se você fizer uma alteração nele.
