### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by rubinho1221** [elizandrodantas/bot-blaze-telegram#40]
![image](https://user-images.githubusercontent.com/98785189/229292626-776e8177-7871-4517-8873-a3adbf26b99a.png)
alguem me consegue ajudar pff

**Comment by rubinho1221** [comment]
ou se alguem me conseguir ajudar a por o tocken etc

**Comment by CentroEducacional-CEC** [comment]
Verifique a Issues fechada que tem um tutorial de instalação!
