### ISSUE TITLE
O sticker do branco.

### ISSUE THREAD

**Issue by DinhoNunesLC** [elizandrodantas/bot-blaze-telegram#5]
O sticker do branco não está sendo enviado, no lugar dele, está a figurinha normal de green na entrada ou no gale!

Fiz a busca pelo arquivo [win-white.jpg](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/sticker/win-white.jpg) no código e não achei nada relacionado a esse arquivo!

**Comment by CentroEducacional-CEC** [comment]
Estou com o mesmo problema! Fiz uma cópia do Green e tentei adicionar o "white" para chamar a figurinha do branco. Mas não surtiu efeito!

**Comment by elizandrodantas** [comment]
as figurinhas são passadas por o usuario nas opções do bot, que esta detalhada em **[OPÇÕES](https://github.com/elizandrodantas/bot-blaze-telegram#op%C3%A7%C3%B5es)**, e tambem tem um exemplo tem mostrando https://prnt.sc/itgUDTzQQkKU

**Comment by DinhoNunesLC** [comment]
Kkkk resposta nada haver com o problema, mas ok! O jeito é aguardar uma solução de alguém da comunidade.

**Comment by elizandrodantas** [comment]
realmente não tinha. @DinhoNunesLC
