### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by jvcunha777** [elizandrodantas/bot-blaze-telegram#6]
O que mudou nessa atualização?

**Comment by elizandrodantas** [comment]
Agora pode ser adicionado algumas opções sem ter que modificar codigo, como:

- Os stickes que seram enviados
- Adicionar tempo para entrar em uma proxima (após win e loss)
- Opção de entrar ou não no branco

Tambem facilitou setar informações que muitos estavam tendo dificuldade, como:

- ID Telegram
- Token bot Telegram

**### Aceitando dicas para implementar no codigo**

**Comment by CentroEducacional-CEC** [comment]
O que acha de adicionar uma opção de resumo dos resultados? Resumo do dia ou do horário!

**Comment by DinhoNunesLC** [comment]
Após essa atualização, o pauseMessage deixou de ser exibido!

**Comment by elizandrodantas** [comment]
> Após essa atualização, o pauseMessage deixou de ser exibido!

A key agora é apenas **message**, acho que esqueci de alterar nos example, sorry. Detalhe da alteração esta em [detalhes](https://github.com/elizandrodantas/bot-blaze-telegram#detalhes)

**Comment by CentroEducacional-CEC** [comment]
Aparentemente está tudo normal, enviando mensagem no privado do bot, a mensagem é excluida e as informações do desenvolvedor são exibidas, mas os sinais não estão sendo enviados no canal quando uso a VPS!

Já em localhost os sinais são enviados!

Estou iniciando com _npm run dev_
 
![Sem Título-1](https://user-images.githubusercontent.com/97736181/189890991-8566e1c1-e10f-491c-bc9e-785977d9d915.png)

**Comment by elizandrodantas** [comment]
> Aparentemente está tudo normal, enviando mensagem no privado do bot, a mensagem é excluida e as informações do desenvolvedor são exibidas, mas os sinais não estão sendo enviados no canal quando uso a VPS!
> 
> Já em localhost os sinais são enviados!
> 
> Estou iniciando com _npm run dev_
> 
> ![Sem Título-1](https://user-images.githubusercontent.com/97736181/189890991-8566e1c1-e10f-491c-bc9e-785977d9d915.png)

As vezes a faixa de ip da vps não tem permissão para acessar sites, como o da blaze. O serviço da heroku, por exemplo, so funcionava com servidor da europa

**Comment by CentroEducacional-CEC** [comment]
Essa é do Canadá, uma BR então a credita que dará certo?

**Comment by elizandrodantas** [comment]
> Essa é do Canadá, uma BR então acredita que dará certo?

Sim
