### ISSUE TITLE
PARADA

### ISSUE THREAD

**Issue by DinhoNunesLC** [elizandrodantas/bot-blaze-telegram#7]
Após cerca de 2 horas ativo, o mesmo para de exibir log de eventos da BLAZE no terminal e para de enviar sinais ao grupo, e nenhuma falha é relatada no terminal.

Usei 3 máquinas diferentes para testar.

Windows 7 32bits
Windows 10 64bits
Ubuntu 18 e 22

**Comment by elizandrodantas** [comment]
Já me relataram isso, só que fiz um grupo com o cara, e deixei rodando uma tarde e uma noite, tudo normal. Caso exibido no console, ficaria fácil resolver, como não é exibido não dá pra saber qual problema. Pode ser um bug, ou erro local

**Comment by elizandrodantas** [comment]
@ybadnews sim, também acho que seja.

**Comment by DinhoNunesLC** [comment]
Apenas Ubuntu é VPS o W7 e W10 são máquinas locais.

Mas tem um porém nessa da api, não iria parar te todos os que tivessem rodando? Deixei um rodando depois de 11:40 e outro iniciei agora depois de 13:00 o de 11:40 parou por volta de 14:00 se fosse a api, os dois deveriam ter parado  juntos, mas o de 13:00 ainda está ok!

**Comment by DinhoNunesLC** [comment]
> Já me relataram isso, só que fiz um grupo com o cara, e deixei rodando uma tarde e uma noite, tudo normal. Caso exibido no console, ficaria fácil resolver, como não é exibido não dá pra saber qual problema. Pode ser um bug, ou erro local

Usei canal e não um grupo! Tem diferença?

**Comment by elizandrodantas** [comment]
> Apenas Ubuntu é VPS o W7 e W10 são máquinas locais.
> 
> Mas tem um porém nessa da api, não iria parar te todos os que tivessem rodando? Deixei um rodando depois de 11:40 e outro iniciei agora depois de 13:00 o de 11:40 parou por volta de 14:00 se fosse a api, os dois deveriam ter parado juntos, mas o de 13:00 ainda está ok!

talvez as conexão socket esteja caindo, pior que nunca aconteceu isso comigo, não tenho como saber onde esta o erro. vou ve se identifico algo na conexão ws

**Comment by elizandrodantas** [comment]
> > Já me relataram isso, só que fiz um grupo com o cara, e deixei rodando uma tarde e uma noite, tudo normal. Caso exibido no console, ficaria fácil resolver, como não é exibido não dá pra saber qual problema. Pode ser um bug, ou erro local
> 
> Usei canal e não um grupo! Tem diferença?

não
