### ISSUE TITLE
Tem Como alguém mim ajuda como eu faço para alterar as estratégias não entendi 

### ISSUE THREAD

**Issue by paulo000100** [elizandrodantas/bot-blaze-telegram#9]

**Comment by marciopoleto** [comment]
eu também não consegui entender qual estratégia ele utiliza.

**Comment by DinhoNunesLC** [comment]
Eu também não encontrei nada, deixei como está, e até que está indo bem!

📊 RESULTADOS 21/09/2022 📈

➡️ ENTRADAS: 25
✅ WINS: 22
❌ LOSS: 0
⚪️ BRANCOS: 3

**Comment by marciopoleto** [comment]
o bot esta ótimo, a ideia de mudar estratégia é pra teste mesmo e alguns horários ou dias específicos, mas mesmo lendo Analise.mjs não consigo entender qual o parâmetro que o bot usa para as escolhas de jogada. no arquivo bot.mjs tem uma parte do código comentada "analisa a possibilidade de entrar na jogada" mas nao entendi também rs... 

nestes resultados do dia 21/09/2022 qual configuração de tempo você utilizou? apos win e o apos loss?

**Comment by DinhoNunesLC** [comment]
A pausa não funciona aqui, mesmo após um loss, win ou Green normal ele não para, só que nesse dia, não deu loss. Normalmente da de 1 a 3 loss nós 25 sinais. Já os brancos de 3 a 12 foi a máxima. Esse bot é insano!

**Comment by elizandrodantas** [comment]
A função [last](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/core/analise.mjs#L34) em [analise.mjs](https://github.com/elizandrodantas/bot-blaze-telegram/blob/main/src/core/analise.mjs) quem é responsavel por as entradas, caso o retorno **verify** da função retorne verdadeiro, ele vai entrar na jogada. A função recebe um parametro **recents** que são as ultimas 20 rodadas da blaze, você pode analizar como queira esses resultados.

@marciopoleto - você pode criar uma verificação de horario dentro da função, que so permite ela analizar em determinados horarios;
@DinhoNunesLC - verifica as configurações, as pausas estão funcionado. Na versão 0.1.35 tinha uma falha na pausa de loss. atualize o codigo e confere se esta entrando nas pausas.

**Comment by DinhoNunesLC** [comment]
Com a "falta das figurinha do gale" nessa nova versão, mantive a versão anterior. A figurinha no meu caso é mais importante que a pausa.

**Comment by felipe0402** [comment]
Como instala esse bot, tô meio perdido aq

**Comment by zenite1996** [comment]
Boa noite, não consigo rodar o bot e ele não envia nenhum sinal no telegram, alguém pode me ajudar?

**Comment by matheusvcarvalho** [comment]
> Boa noite, não consigo rodar o bot e ele não envia nenhum sinal no telegram, alguém pode me ajudar?

Posso te ajudar a rodar o bot se quiser. 
Quanto a analise eu também não entendi como funciona a análise dele.

**Comment by zenite1996** [comment]
Opa amigo obrigado pela disponibilidade


matheusvcarvalho ***@***.***> escreveu no dia segunda,
17/10/2022 à(s) 20:40:

**Comment by matheusvcarvalho** [comment]
> Opa amigo obrigado pela disponibilidade 

Me chama no telegram, q vc me fala qual erro q ta dando e te falo
https://t.me/xwebsx

**Comment by ThiagoCamargo6** [comment]
Pessoal alguém conseguiu alterar as estratégias? Queria alterar mas também não entendi como ele se baseia nas estratégias pra fazer as entradas.
